import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  upc: {
    backgroundColor: '#faf5ff',
    borderRadius: 24,
    overflow: 'hidden',
    margin: 16,
    elevation: 10,
    shadowColor: '#a78bfa',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  header: {
    height: 160,
    backgroundColor: '#ede9fe',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  starOne: {
    fontSize: 80,
    color: '#c084fc',
    position: 'absolute',
    top: 5,
    left: 20,
  },
  starTwo: {
    fontSize: 60,
    color: '#a78bfa',
    position: 'absolute',
    bottom: -10,
    right: 25,
  },
  starThree: {
    fontSize: 45,
    color: '#7c3aed',
    position: 'absolute',
    bottom: 20,
    left: 60,
  },
  profileDown: {
    alignItems: 'center',
    padding: 24,
  },
  profileImageWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: -70,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  glowRing: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#c084fc',
    opacity: 0.4,
    shadowColor: '#c084fc',
    shadowOpacity: 0.9,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 0 },
  },
  profileImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  profileName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4c1d95',
    marginTop: 8,
    marginBottom: 6,
  },
  profileUsername: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7c3aed',
    marginBottom: 6,
  },
  profileBio: {
    fontSize: 15,
    color: '#5b21b6',
    textAlign: 'center',
    marginVertical: 10,
    paddingHorizontal: 25,
    lineHeight: 21,
  },
  profileCourse: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6d28d9',
    marginTop: 6,
  },
  divider: {
    width: '80%',
    height: 1,
    backgroundColor: '#ddd6fe',
    marginVertical: 8,
    borderRadius: 2,
  },
})

export default styles
